name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    # We want to run right after the `latest` image is published.
    # So, let's do it an hour right after. Look the schedule of publishing here:
    # https://github.com/alexhumphreys/idris2-dockerfile/blob/main/.github/workflows/docker-image.yml
    - cron: '0 1 * * *'

defaults:
  run:
    shell: bash

jobs:

  build:
    name: Build the lib with Idris2 HEAD
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container: snazzybucket/idris2:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build lib
        run: make lib
      - name: Build docs
        run: make docs
